#!/usr/bin/env python3
"""Rebuild glossary.md: every law name, alphabetical, with its ID, level and source file.

    python scripts/build_glossary.py

Run it after adding or editing a file in sources/ (part of the Fold-in procedure).
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADING = re.compile(r"^### ([A-Z0-9]+-\d+) (.+?)\s*(🟢|🟠|🔴)?\s*$")


def entries() -> list[tuple[str, str, str, str]]:
    found = []
    for path in sorted((ROOT / "sources").glob("*.md")):
        title = path.read_text(encoding="utf-8").splitlines()[0].lstrip("# ").strip()
        for line in path.read_text(encoding="utf-8").splitlines():
            match = HEADING.match(line)
            if match:
                law_id, name, level = match.group(1), match.group(2), match.group(3) or ""
                found.append((name, law_id, level, f"sources/{path.name} ({title})"))
    return found


def sort_key(entry: tuple[str, str, str, str]) -> str:
    # "Law 9: Win through..." sorts under its name, not under "Law".
    name = re.sub(r"^Law \d+:\s*", "", entry[0])
    return re.sub(r"^(the|a|an)\s+", "", name.strip('"').lower())


def main() -> None:
    lines = [
        "# Glossary: every law by name",
        "",
        "Generated by `scripts/build_glossary.py` from the headings in `sources/`. Do not edit by hand.",
        "",
    ]
    for name, law_id, level, source in sorted(entries(), key=sort_key):
        lines.append(f"- **{name}**: {law_id} {level}, {source}")
    (ROOT / "glossary.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"glossary.md: {len(lines) - 4} entries")


if __name__ == "__main__":
    main()
